//
//  main.swift
//  Parasol
//
//  Created by Kyle McAlpine on 30/12/2015.
//  Copyright © 2015 Loot Financial Services Ltd. All rights reserved.
//

import Foundation

// TODO: make passing Xcode project as an optional argument
if let xcodeProject = XcodeProject.findXcodeProjectInCurrentDirectory() {
    if case let .Exists(profdataPath, executablePath) = xcodeProject.coverageDataExists {
        Coverage.showCoverage(profdataPath, executablePath: executablePath)
    } else {
        print("Coverage data has not been generated. Would you like to run tests? (y/n)")
        let input = readLine()
        if input == "y" {
            xcodeProject.runTests()
            if case let .Exists(profdataPath, executablePath) = xcodeProject.coverageDataExists {
                Coverage.showCoverage(profdataPath, executablePath: executablePath)
            } else {
                print("ERROR: Coverage data was not generated by Xcode.")
            }
        } else if input == "n" {
            
        }
    }
} else {
    print("Couldn't find an Xcode project")
}


